// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: ledger/v1/api.proto

package ledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_CreateLedger_FullMethodName          = "/ledger.v1.LedgerService/CreateLedger"
	LedgerService_GetLedger_FullMethodName             = "/ledger.v1.LedgerService/GetLedger"
	LedgerService_ListLedgers_FullMethodName           = "/ledger.v1.LedgerService/ListLedgers"
	LedgerService_SealLedger_FullMethodName            = "/ledger.v1.LedgerService/SealLedger"
	LedgerService_Submit_FullMethodName                = "/ledger.v1.LedgerService/Submit"
	LedgerService_GetTransaction_FullMethodName        = "/ledger.v1.LedgerService/GetTransaction"
	LedgerService_ListTransactions_FullMethodName      = "/ledger.v1.LedgerService/ListTransactions"
	LedgerService_GetAccount_FullMethodName            = "/ledger.v1.LedgerService/GetAccount"
	LedgerService_ListAccounts_FullMethodName          = "/ledger.v1.LedgerService/ListAccounts"
	LedgerService_GetBalance_FullMethodName            = "/ledger.v1.LedgerService/GetBalance"
	LedgerService_GetAggregatedBalances_FullMethodName = "/ledger.v1.LedgerService/GetAggregatedBalances"
	LedgerService_GetHold_FullMethodName               = "/ledger.v1.LedgerService/GetHold"
	LedgerService_ListHolds_FullMethodName             = "/ledger.v1.LedgerService/ListHolds"
	LedgerService_GetRelationships_FullMethodName      = "/ledger.v1.LedgerService/GetRelationships"
	LedgerService_ListLogEvents_FullMethodName         = "/ledger.v1.LedgerService/ListLogEvents"
	LedgerService_GetLogEvent_FullMethodName           = "/ledger.v1.LedgerService/GetLogEvent"
	LedgerService_VerifyBatch_FullMethodName           = "/ledger.v1.LedgerService/VerifyBatch"
	LedgerService_InsertSchema_FullMethodName          = "/ledger.v1.LedgerService/InsertSchema"
	LedgerService_GetSchema_FullMethodName             = "/ledger.v1.LedgerService/GetSchema"
	LedgerService_SubmitForApproval_FullMethodName     = "/ledger.v1.LedgerService/SubmitForApproval"
	LedgerService_ApproveIntent_FullMethodName         = "/ledger.v1.LedgerService/ApproveIntent"
	LedgerService_ListPendingApprovals_FullMethodName  = "/ledger.v1.LedgerService/ListPendingApprovals"
	LedgerService_Subscribe_FullMethodName             = "/ledger.v1.LedgerService/Subscribe"
	LedgerService_Export_FullMethodName                = "/ledger.v1.LedgerService/Export"
	LedgerService_Import_FullMethodName                = "/ledger.v1.LedgerService/Import"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	// Ledger lifecycle
	CreateLedger(ctx context.Context, in *CreateLedgerRequest, opts ...grpc.CallOption) (*Ledger, error)
	GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*Ledger, error)
	ListLedgers(ctx context.Context, in *ListLedgersRequest, opts ...grpc.CallOption) (*ListLedgersResponse, error)
	SealLedger(ctx context.Context, in *SealLedgerRequest, opts ...grpc.CallOption) (*Ledger, error)
	// Submit operations (universal write endpoint)
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// Reads
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	GetAggregatedBalances(ctx context.Context, in *GetAggregatedBalancesRequest, opts ...grpc.CallOption) (*GetAggregatedBalancesResponse, error)
	GetHold(ctx context.Context, in *GetHoldRequest, opts ...grpc.CallOption) (*Hold, error)
	ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error)
	GetRelationships(ctx context.Context, in *GetRelationshipsRequest, opts ...grpc.CallOption) (*GetRelationshipsResponse, error)
	// Log
	ListLogEvents(ctx context.Context, in *ListLogEventsRequest, opts ...grpc.CallOption) (*ListLogEventsResponse, error)
	GetLogEvent(ctx context.Context, in *GetLogEventRequest, opts ...grpc.CallOption) (*LogEvent, error)
	VerifyBatch(ctx context.Context, in *VerifyBatchRequest, opts ...grpc.CallOption) (*VerifyBatchResponse, error)
	// Schemas
	InsertSchema(ctx context.Context, in *InsertSchemaRequest, opts ...grpc.CallOption) (*Schema, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*Schema, error)
	// Approvals
	SubmitForApproval(ctx context.Context, in *SubmitForApprovalRequest, opts ...grpc.CallOption) (*SubmitForApprovalResponse, error)
	ApproveIntent(ctx context.Context, in *ApproveIntentRequest, opts ...grpc.CallOption) (*ApproveIntentResponse, error)
	ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListPendingApprovalsResponse, error)
	// Streaming subscriptions
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error)
	// Export/Import
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error)
	Import(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, ImportResponse], error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) CreateLedger(ctx context.Context, in *CreateLedgerRequest, opts ...grpc.CallOption) (*Ledger, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ledger)
	err := c.cc.Invoke(ctx, LedgerService_CreateLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*Ledger, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ledger)
	err := c.cc.Invoke(ctx, LedgerService_GetLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListLedgers(ctx context.Context, in *ListLedgersRequest, opts ...grpc.CallOption) (*ListLedgersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLedgersResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListLedgers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SealLedger(ctx context.Context, in *SealLedgerRequest, opts ...grpc.CallOption) (*Ledger, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ledger)
	err := c.cc.Invoke(ctx, LedgerService_SealLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, LedgerService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, LedgerService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, LedgerService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetAggregatedBalances(ctx context.Context, in *GetAggregatedBalancesRequest, opts ...grpc.CallOption) (*GetAggregatedBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAggregatedBalancesResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetAggregatedBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetHold(ctx context.Context, in *GetHoldRequest, opts ...grpc.CallOption) (*Hold, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hold)
	err := c.cc.Invoke(ctx, LedgerService_GetHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHoldsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListHolds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetRelationships(ctx context.Context, in *GetRelationshipsRequest, opts ...grpc.CallOption) (*GetRelationshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationshipsResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListLogEvents(ctx context.Context, in *ListLogEventsRequest, opts ...grpc.CallOption) (*ListLogEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLogEventsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListLogEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLogEvent(ctx context.Context, in *GetLogEventRequest, opts ...grpc.CallOption) (*LogEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogEvent)
	err := c.cc.Invoke(ctx, LedgerService_GetLogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) VerifyBatch(ctx context.Context, in *VerifyBatchRequest, opts ...grpc.CallOption) (*VerifyBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyBatchResponse)
	err := c.cc.Invoke(ctx, LedgerService_VerifyBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) InsertSchema(ctx context.Context, in *InsertSchemaRequest, opts ...grpc.CallOption) (*Schema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Schema)
	err := c.cc.Invoke(ctx, LedgerService_InsertSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*Schema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Schema)
	err := c.cc.Invoke(ctx, LedgerService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SubmitForApproval(ctx context.Context, in *SubmitForApprovalRequest, opts ...grpc.CallOption) (*SubmitForApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitForApprovalResponse)
	err := c.cc.Invoke(ctx, LedgerService_SubmitForApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ApproveIntent(ctx context.Context, in *ApproveIntentRequest, opts ...grpc.CallOption) (*ApproveIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveIntentResponse)
	err := c.cc.Invoke(ctx, LedgerService_ApproveIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListPendingApprovalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingApprovalsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListPendingApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[0], LedgerService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscriptionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_SubscribeClient = grpc.ServerStreamingClient[SubscriptionEvent]

func (c *ledgerServiceClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[1], LedgerService_Export_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportRequest, LogEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_ExportClient = grpc.ServerStreamingClient[LogEvent]

func (c *ledgerServiceClient) Import(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEvent, ImportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[2], LedgerService_Import_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEvent, ImportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_ImportClient = grpc.ClientStreamingClient[LogEvent, ImportResponse]

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	// Ledger lifecycle
	CreateLedger(context.Context, *CreateLedgerRequest) (*Ledger, error)
	GetLedger(context.Context, *GetLedgerRequest) (*Ledger, error)
	ListLedgers(context.Context, *ListLedgersRequest) (*ListLedgersResponse, error)
	SealLedger(context.Context, *SealLedgerRequest) (*Ledger, error)
	// Submit operations (universal write endpoint)
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	// Reads
	GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error)
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	GetAggregatedBalances(context.Context, *GetAggregatedBalancesRequest) (*GetAggregatedBalancesResponse, error)
	GetHold(context.Context, *GetHoldRequest) (*Hold, error)
	ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error)
	GetRelationships(context.Context, *GetRelationshipsRequest) (*GetRelationshipsResponse, error)
	// Log
	ListLogEvents(context.Context, *ListLogEventsRequest) (*ListLogEventsResponse, error)
	GetLogEvent(context.Context, *GetLogEventRequest) (*LogEvent, error)
	VerifyBatch(context.Context, *VerifyBatchRequest) (*VerifyBatchResponse, error)
	// Schemas
	InsertSchema(context.Context, *InsertSchemaRequest) (*Schema, error)
	GetSchema(context.Context, *GetSchemaRequest) (*Schema, error)
	// Approvals
	SubmitForApproval(context.Context, *SubmitForApprovalRequest) (*SubmitForApprovalResponse, error)
	ApproveIntent(context.Context, *ApproveIntentRequest) (*ApproveIntentResponse, error)
	ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error)
	// Streaming subscriptions
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscriptionEvent]) error
	// Export/Import
	Export(*ExportRequest, grpc.ServerStreamingServer[LogEvent]) error
	Import(grpc.ClientStreamingServer[LogEvent, ImportResponse]) error
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) CreateLedger(context.Context, *CreateLedgerRequest) (*Ledger, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLedger not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedger(context.Context, *GetLedgerRequest) (*Ledger, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedger not implemented")
}
func (UnimplementedLedgerServiceServer) ListLedgers(context.Context, *ListLedgersRequest) (*ListLedgersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLedgers not implemented")
}
func (UnimplementedLedgerServiceServer) SealLedger(context.Context, *SealLedgerRequest) (*Ledger, error) {
	return nil, status.Error(codes.Unimplemented, "method SealLedger not implemented")
}
func (UnimplementedLedgerServiceServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedLedgerServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedLedgerServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedLedgerServiceServer) GetAccount(context.Context, *GetAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedLedgerServiceServer) ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedLedgerServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedLedgerServiceServer) GetAggregatedBalances(context.Context, *GetAggregatedBalancesRequest) (*GetAggregatedBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAggregatedBalances not implemented")
}
func (UnimplementedLedgerServiceServer) GetHold(context.Context, *GetHoldRequest) (*Hold, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHold not implemented")
}
func (UnimplementedLedgerServiceServer) ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHolds not implemented")
}
func (UnimplementedLedgerServiceServer) GetRelationships(context.Context, *GetRelationshipsRequest) (*GetRelationshipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelationships not implemented")
}
func (UnimplementedLedgerServiceServer) ListLogEvents(context.Context, *ListLogEventsRequest) (*ListLogEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLogEvents not implemented")
}
func (UnimplementedLedgerServiceServer) GetLogEvent(context.Context, *GetLogEventRequest) (*LogEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogEvent not implemented")
}
func (UnimplementedLedgerServiceServer) VerifyBatch(context.Context, *VerifyBatchRequest) (*VerifyBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyBatch not implemented")
}
func (UnimplementedLedgerServiceServer) InsertSchema(context.Context, *InsertSchemaRequest) (*Schema, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertSchema not implemented")
}
func (UnimplementedLedgerServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*Schema, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedLedgerServiceServer) SubmitForApproval(context.Context, *SubmitForApprovalRequest) (*SubmitForApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitForApproval not implemented")
}
func (UnimplementedLedgerServiceServer) ApproveIntent(context.Context, *ApproveIntentRequest) (*ApproveIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveIntent not implemented")
}
func (UnimplementedLedgerServiceServer) ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingApprovals not implemented")
}
func (UnimplementedLedgerServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscriptionEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLedgerServiceServer) Export(*ExportRequest, grpc.ServerStreamingServer[LogEvent]) error {
	return status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedLedgerServiceServer) Import(grpc.ClientStreamingServer[LogEvent, ImportResponse]) error {
	return status.Error(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_CreateLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CreateLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateLedger(ctx, req.(*CreateLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedger(ctx, req.(*GetLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListLedgers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListLedgers(ctx, req.(*ListLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SealLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).SealLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_SealLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).SealLedger(ctx, req.(*SealLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetAggregatedBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAggregatedBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetAggregatedBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetAggregatedBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetAggregatedBalances(ctx, req.(*GetAggregatedBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetHold(ctx, req.(*GetHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListHolds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHoldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListHolds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListHolds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListHolds(ctx, req.(*ListHoldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetRelationships(ctx, req.(*GetRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListLogEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLogEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListLogEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListLogEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListLogEvents(ctx, req.(*ListLogEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLogEvent(ctx, req.(*GetLogEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_VerifyBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).VerifyBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_VerifyBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).VerifyBatch(ctx, req.(*VerifyBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_InsertSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).InsertSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_InsertSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).InsertSchema(ctx, req.(*InsertSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SubmitForApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitForApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).SubmitForApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_SubmitForApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).SubmitForApproval(ctx, req.(*SubmitForApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ApproveIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ApproveIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ApproveIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ApproveIntent(ctx, req.(*ApproveIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListPendingApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListPendingApprovals(ctx, req.(*ListPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscriptionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_SubscribeServer = grpc.ServerStreamingServer[SubscriptionEvent]

func _LedgerService_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).Export(m, &grpc.GenericServerStream[ExportRequest, LogEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_ExportServer = grpc.ServerStreamingServer[LogEvent]

func _LedgerService_Import_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LedgerServiceServer).Import(&grpc.GenericServerStream[LogEvent, ImportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LedgerService_ImportServer = grpc.ClientStreamingServer[LogEvent, ImportResponse]

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLedger",
			Handler:    _LedgerService_CreateLedger_Handler,
		},
		{
			MethodName: "GetLedger",
			Handler:    _LedgerService_GetLedger_Handler,
		},
		{
			MethodName: "ListLedgers",
			Handler:    _LedgerService_ListLedgers_Handler,
		},
		{
			MethodName: "SealLedger",
			Handler:    _LedgerService_SealLedger_Handler,
		},
		{
			MethodName: "Submit",
			Handler:    _LedgerService_Submit_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _LedgerService_GetTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _LedgerService_ListTransactions_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _LedgerService_GetAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _LedgerService_ListAccounts_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _LedgerService_GetBalance_Handler,
		},
		{
			MethodName: "GetAggregatedBalances",
			Handler:    _LedgerService_GetAggregatedBalances_Handler,
		},
		{
			MethodName: "GetHold",
			Handler:    _LedgerService_GetHold_Handler,
		},
		{
			MethodName: "ListHolds",
			Handler:    _LedgerService_ListHolds_Handler,
		},
		{
			MethodName: "GetRelationships",
			Handler:    _LedgerService_GetRelationships_Handler,
		},
		{
			MethodName: "ListLogEvents",
			Handler:    _LedgerService_ListLogEvents_Handler,
		},
		{
			MethodName: "GetLogEvent",
			Handler:    _LedgerService_GetLogEvent_Handler,
		},
		{
			MethodName: "VerifyBatch",
			Handler:    _LedgerService_VerifyBatch_Handler,
		},
		{
			MethodName: "InsertSchema",
			Handler:    _LedgerService_InsertSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _LedgerService_GetSchema_Handler,
		},
		{
			MethodName: "SubmitForApproval",
			Handler:    _LedgerService_SubmitForApproval_Handler,
		},
		{
			MethodName: "ApproveIntent",
			Handler:    _LedgerService_ApproveIntent_Handler,
		},
		{
			MethodName: "ListPendingApprovals",
			Handler:    _LedgerService_ListPendingApprovals_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _LedgerService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Export",
			Handler:       _LedgerService_Export_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Import",
			Handler:       _LedgerService_Import_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ledger/v1/api.proto",
}
