// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ledger/v1/events.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_UNSPECIFIED    EventType = 0
	EventType_TRANSACTION_POSTED   EventType = 1
	EventType_HOLD_AUTHORIZED      EventType = 2
	EventType_HOLD_CAPTURED        EventType = 3
	EventType_HOLD_VOIDED          EventType = 4
	EventType_HOLD_EXPIRED         EventType = 5
	EventType_CONVERSION_RECORDED  EventType = 6
	EventType_TRANSACTION_REVERTED EventType = 7
	EventType_TRANSACTION_AMENDED  EventType = 8
	EventType_METADATA_SET         EventType = 9
	EventType_METADATA_DELETED     EventType = 10
	EventType_SCHEMA_INSERTED      EventType = 11
	EventType_POLICY_DENIAL        EventType = 12
	EventType_APPROVAL_RECORDED    EventType = 13
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_UNSPECIFIED",
		1:  "TRANSACTION_POSTED",
		2:  "HOLD_AUTHORIZED",
		3:  "HOLD_CAPTURED",
		4:  "HOLD_VOIDED",
		5:  "HOLD_EXPIRED",
		6:  "CONVERSION_RECORDED",
		7:  "TRANSACTION_REVERTED",
		8:  "TRANSACTION_AMENDED",
		9:  "METADATA_SET",
		10: "METADATA_DELETED",
		11: "SCHEMA_INSERTED",
		12: "POLICY_DENIAL",
		13: "APPROVAL_RECORDED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNSPECIFIED":    0,
		"TRANSACTION_POSTED":   1,
		"HOLD_AUTHORIZED":      2,
		"HOLD_CAPTURED":        3,
		"HOLD_VOIDED":          4,
		"HOLD_EXPIRED":         5,
		"CONVERSION_RECORDED":  6,
		"TRANSACTION_REVERTED": 7,
		"TRANSACTION_AMENDED":  8,
		"METADATA_SET":         9,
		"METADATA_DELETED":     10,
		"SCHEMA_INSERTED":      11,
		"POLICY_DENIAL":        12,
		"APPROVAL_RECORDED":    13,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_ledger_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{0}
}

type LogEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	LedgerId        string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	LedgerSeq       uint64                 `protobuf:"varint,3,opt,name=ledger_seq,json=ledgerSeq,proto3" json:"ledger_seq,omitempty"`
	SystemTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=system_time,json=systemTime,proto3" json:"system_time,omitempty"`
	ValidTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	IdempotencyHash string                 `protobuf:"bytes,7,opt,name=idempotency_hash,json=idempotencyHash,proto3" json:"idempotency_hash,omitempty"`
	BatchId         string                 `protobuf:"bytes,8,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Payload         []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Type            EventType              `protobuf:"varint,10,opt,name=type,proto3,enum=ledger.v1.EventType" json:"type,omitempty"`
	SchemaVersion   uint64                 `protobuf:"varint,11,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_ledger_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LogEvent) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *LogEvent) GetLedgerSeq() uint64 {
	if x != nil {
		return x.LedgerSeq
	}
	return 0
}

func (x *LogEvent) GetSystemTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SystemTime
	}
	return nil
}

func (x *LogEvent) GetValidTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTime
	}
	return nil
}

func (x *LogEvent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LogEvent) GetIdempotencyHash() string {
	if x != nil {
		return x.IdempotencyHash
	}
	return ""
}

func (x *LogEvent) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *LogEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNSPECIFIED
}

func (x *LogEvent) GetSchemaVersion() uint64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type TransactionPostedPayload struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TransactionId string                    `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Postings      []*Posting                `protobuf:"bytes,2,rep,name=postings,proto3" json:"postings,omitempty"`
	Metadata      map[string]*MetadataValue `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Reference     string                    `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionPostedPayload) Reset() {
	*x = TransactionPostedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionPostedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPostedPayload) ProtoMessage() {}

func (x *TransactionPostedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPostedPayload.ProtoReflect.Descriptor instead.
func (*TransactionPostedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionPostedPayload) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionPostedPayload) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *TransactionPostedPayload) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransactionPostedPayload) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type HoldAuthorizedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HoldId          string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	DestinationHint string                 `protobuf:"bytes,3,opt,name=destination_hint,json=destinationHint,proto3" json:"destination_hint,omitempty"`
	Amount          string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset           string                 `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HoldAuthorizedPayload) Reset() {
	*x = HoldAuthorizedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldAuthorizedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldAuthorizedPayload) ProtoMessage() {}

func (x *HoldAuthorizedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldAuthorizedPayload.ProtoReflect.Descriptor instead.
func (*HoldAuthorizedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *HoldAuthorizedPayload) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *HoldAuthorizedPayload) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HoldAuthorizedPayload) GetDestinationHint() string {
	if x != nil {
		return x.DestinationHint
	}
	return ""
}

func (x *HoldAuthorizedPayload) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *HoldAuthorizedPayload) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *HoldAuthorizedPayload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type HoldCapturedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptureId     string                 `protobuf:"bytes,1,opt,name=capture_id,json=captureId,proto3" json:"capture_id,omitempty"`
	HoldId        string                 `protobuf:"bytes,2,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldCapturedPayload) Reset() {
	*x = HoldCapturedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldCapturedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldCapturedPayload) ProtoMessage() {}

func (x *HoldCapturedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldCapturedPayload.ProtoReflect.Descriptor instead.
func (*HoldCapturedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *HoldCapturedPayload) GetCaptureId() string {
	if x != nil {
		return x.CaptureId
	}
	return ""
}

func (x *HoldCapturedPayload) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *HoldCapturedPayload) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *HoldCapturedPayload) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type HoldVoidedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldVoidedPayload) Reset() {
	*x = HoldVoidedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldVoidedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldVoidedPayload) ProtoMessage() {}

func (x *HoldVoidedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldVoidedPayload.ProtoReflect.Descriptor instead.
func (*HoldVoidedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *HoldVoidedPayload) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *HoldVoidedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HoldExpiredPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldExpiredPayload) Reset() {
	*x = HoldExpiredPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldExpiredPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldExpiredPayload) ProtoMessage() {}

func (x *HoldExpiredPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldExpiredPayload.ProtoReflect.Descriptor instead.
func (*HoldExpiredPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *HoldExpiredPayload) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ConversionRecordedPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConversionId      string                 `protobuf:"bytes,1,opt,name=conversion_id,json=conversionId,proto3" json:"conversion_id,omitempty"`
	Source            string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination       string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	SourceAmount      string                 `protobuf:"bytes,4,opt,name=source_amount,json=sourceAmount,proto3" json:"source_amount,omitempty"`
	SourceAsset       string                 `protobuf:"bytes,5,opt,name=source_asset,json=sourceAsset,proto3" json:"source_asset,omitempty"`
	DestinationAmount string                 `protobuf:"bytes,6,opt,name=destination_amount,json=destinationAmount,proto3" json:"destination_amount,omitempty"`
	DestinationAsset  string                 `protobuf:"bytes,7,opt,name=destination_asset,json=destinationAsset,proto3" json:"destination_asset,omitempty"`
	Rate              string                 `protobuf:"bytes,8,opt,name=rate,proto3" json:"rate,omitempty"`
	RateSource        string                 `protobuf:"bytes,9,opt,name=rate_source,json=rateSource,proto3" json:"rate_source,omitempty"`
	SlippageAccount   string                 `protobuf:"bytes,10,opt,name=slippage_account,json=slippageAccount,proto3" json:"slippage_account,omitempty"`
	SlippageAmount    string                 `protobuf:"bytes,11,opt,name=slippage_amount,json=slippageAmount,proto3" json:"slippage_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversionRecordedPayload) Reset() {
	*x = ConversionRecordedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversionRecordedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversionRecordedPayload) ProtoMessage() {}

func (x *ConversionRecordedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversionRecordedPayload.ProtoReflect.Descriptor instead.
func (*ConversionRecordedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *ConversionRecordedPayload) GetConversionId() string {
	if x != nil {
		return x.ConversionId
	}
	return ""
}

func (x *ConversionRecordedPayload) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConversionRecordedPayload) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ConversionRecordedPayload) GetSourceAmount() string {
	if x != nil {
		return x.SourceAmount
	}
	return ""
}

func (x *ConversionRecordedPayload) GetSourceAsset() string {
	if x != nil {
		return x.SourceAsset
	}
	return ""
}

func (x *ConversionRecordedPayload) GetDestinationAmount() string {
	if x != nil {
		return x.DestinationAmount
	}
	return ""
}

func (x *ConversionRecordedPayload) GetDestinationAsset() string {
	if x != nil {
		return x.DestinationAsset
	}
	return ""
}

func (x *ConversionRecordedPayload) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ConversionRecordedPayload) GetRateSource() string {
	if x != nil {
		return x.RateSource
	}
	return ""
}

func (x *ConversionRecordedPayload) GetSlippageAccount() string {
	if x != nil {
		return x.SlippageAccount
	}
	return ""
}

func (x *ConversionRecordedPayload) GetSlippageAmount() string {
	if x != nil {
		return x.SlippageAmount
	}
	return ""
}

type TransactionRevertedPayload struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OriginalTransactionId  string                 `protobuf:"bytes,1,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	RevertingTransactionId string                 `protobuf:"bytes,2,opt,name=reverting_transaction_id,json=revertingTransactionId,proto3" json:"reverting_transaction_id,omitempty"`
	Reason                 string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Force                  bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransactionRevertedPayload) Reset() {
	*x = TransactionRevertedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRevertedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRevertedPayload) ProtoMessage() {}

func (x *TransactionRevertedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRevertedPayload.ProtoReflect.Descriptor instead.
func (*TransactionRevertedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionRevertedPayload) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

func (x *TransactionRevertedPayload) GetRevertingTransactionId() string {
	if x != nil {
		return x.RevertingTransactionId
	}
	return ""
}

func (x *TransactionRevertedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransactionRevertedPayload) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TransactionAmendedPayload struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	OriginalTransactionId string                    `protobuf:"bytes,1,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	MetadataChanges       map[string]*MetadataValue `protobuf:"bytes,2,rep,name=metadata_changes,json=metadataChanges,proto3" json:"metadata_changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransactionAmendedPayload) Reset() {
	*x = TransactionAmendedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAmendedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAmendedPayload) ProtoMessage() {}

func (x *TransactionAmendedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAmendedPayload.ProtoReflect.Descriptor instead.
func (*TransactionAmendedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionAmendedPayload) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

func (x *TransactionAmendedPayload) GetMetadataChanges() map[string]*MetadataValue {
	if x != nil {
		return x.MetadataChanges
	}
	return nil
}

type MetadataSetPayload struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TargetType    string                    `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                    `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Metadata      map[string]*MetadataValue `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataSetPayload) Reset() {
	*x = MetadataSetPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataSetPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataSetPayload) ProtoMessage() {}

func (x *MetadataSetPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataSetPayload.ProtoReflect.Descriptor instead.
func (*MetadataSetPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *MetadataSetPayload) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *MetadataSetPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MetadataSetPayload) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetadataDeletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataDeletedPayload) Reset() {
	*x = MetadataDeletedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataDeletedPayload) ProtoMessage() {}

func (x *MetadataDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataDeletedPayload.ProtoReflect.Descriptor instead.
func (*MetadataDeletedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataDeletedPayload) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *MetadataDeletedPayload) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MetadataDeletedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SchemaInsertedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SchemaBytes   []byte                 `protobuf:"bytes,2,opt,name=schema_bytes,json=schemaBytes,proto3" json:"schema_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaInsertedPayload) Reset() {
	*x = SchemaInsertedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInsertedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInsertedPayload) ProtoMessage() {}

func (x *SchemaInsertedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInsertedPayload.ProtoReflect.Descriptor instead.
func (*SchemaInsertedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *SchemaInsertedPayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SchemaInsertedPayload) GetSchemaBytes() []byte {
	if x != nil {
		return x.SchemaBytes
	}
	return nil
}

type PolicyDenialPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	IntentHash    string                 `protobuf:"bytes,2,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyDenialPayload) Reset() {
	*x = PolicyDenialPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDenialPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDenialPayload) ProtoMessage() {}

func (x *PolicyDenialPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDenialPayload.ProtoReflect.Descriptor instead.
func (*PolicyDenialPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *PolicyDenialPayload) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *PolicyDenialPayload) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *PolicyDenialPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApprovalRecordedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Principal     string                 `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRecordedPayload) Reset() {
	*x = ApprovalRecordedPayload{}
	mi := &file_ledger_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRecordedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRecordedPayload) ProtoMessage() {}

func (x *ApprovalRecordedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRecordedPayload.ProtoReflect.Descriptor instead.
func (*ApprovalRecordedPayload) Descriptor() ([]byte, []int) {
	return file_ledger_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *ApprovalRecordedPayload) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ApprovalRecordedPayload) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *ApprovalRecordedPayload) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_ledger_v1_events_proto protoreflect.FileDescriptor

const file_ledger_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/events.proto\x12\tledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12ledger/v1/ir.proto\"\xb3\x03\n" +
	"\bLogEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x1d\n" +
	"\n" +
	"ledger_seq\x18\x03 \x01(\x04R\tledgerSeq\x12;\n" +
	"\vsystem_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"systemTime\x129\n" +
	"\n" +
	"valid_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidTime\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10idempotency_hash\x18\a \x01(\tR\x0fidempotencyHash\x12\x19\n" +
	"\bbatch_id\x18\b \x01(\tR\abatchId\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12(\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x14.ledger.v1.EventTypeR\x04type\x12%\n" +
	"\x0eschema_version\x18\v \x01(\x04R\rschemaVersion\"\xb5\x02\n" +
	"\x18TransactionPostedPayload\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12.\n" +
	"\bpostings\x18\x02 \x03(\v2\x12.ledger.v1.PostingR\bpostings\x12M\n" +
	"\bmetadata\x18\x03 \x03(\v21.ledger.v1.TransactionPostedPayload.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\treference\x18\x04 \x01(\tR\treference\x1aU\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ledger.v1.MetadataValueR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x15HoldAuthorizedPayload\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12)\n" +
	"\x10destination_hint\x18\x03 \x01(\tR\x0fdestinationHint\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x05 \x01(\tR\x05asset\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x87\x01\n" +
	"\x13HoldCapturedPayload\x12\x1d\n" +
	"\n" +
	"capture_id\x18\x01 \x01(\tR\tcaptureId\x12\x17\n" +
	"\ahold_id\x18\x02 \x01(\tR\x06holdId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\"D\n" +
	"\x11HoldVoidedPayload\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"-\n" +
	"\x12HoldExpiredPayload\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"\xa7\x03\n" +
	"\x19ConversionRecordedPayload\x12#\n" +
	"\rconversion_id\x18\x01 \x01(\tR\fconversionId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12#\n" +
	"\rsource_amount\x18\x04 \x01(\tR\fsourceAmount\x12!\n" +
	"\fsource_asset\x18\x05 \x01(\tR\vsourceAsset\x12-\n" +
	"\x12destination_amount\x18\x06 \x01(\tR\x11destinationAmount\x12+\n" +
	"\x11destination_asset\x18\a \x01(\tR\x10destinationAsset\x12\x12\n" +
	"\x04rate\x18\b \x01(\tR\x04rate\x12\x1f\n" +
	"\vrate_source\x18\t \x01(\tR\n" +
	"rateSource\x12)\n" +
	"\x10slippage_account\x18\n" +
	" \x01(\tR\x0fslippageAccount\x12'\n" +
	"\x0fslippage_amount\x18\v \x01(\tR\x0eslippageAmount\"\xbc\x01\n" +
	"\x1aTransactionRevertedPayload\x126\n" +
	"\x17original_transaction_id\x18\x01 \x01(\tR\x15originalTransactionId\x128\n" +
	"\x18reverting_transaction_id\x18\x02 \x01(\tR\x16revertingTransactionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\x97\x02\n" +
	"\x19TransactionAmendedPayload\x126\n" +
	"\x17original_transaction_id\x18\x01 \x01(\tR\x15originalTransactionId\x12d\n" +
	"\x10metadata_changes\x18\x02 \x03(\v29.ledger.v1.TransactionAmendedPayload.MetadataChangesEntryR\x0fmetadataChanges\x1a\\\n" +
	"\x14MetadataChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ledger.v1.MetadataValueR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x12MetadataSetPayload\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.ledger.v1.MetadataSetPayload.MetadataEntryR\bmetadata\x1aU\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ledger.v1.MetadataValueR\x05value:\x028\x01\"h\n" +
	"\x16MetadataDeletedPayload\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"T\n" +
	"\x15SchemaInsertedPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fschema_bytes\x18\x02 \x01(\fR\vschemaBytes\"l\n" +
	"\x13PolicyDenialPayload\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x1f\n" +
	"\vintent_hash\x18\x02 \x01(\tR\n" +
	"intentHash\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"r\n" +
	"\x17ApprovalRecordedPayload\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature*\xb8\x02\n" +
	"\tEventType\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRANSACTION_POSTED\x10\x01\x12\x13\n" +
	"\x0fHOLD_AUTHORIZED\x10\x02\x12\x11\n" +
	"\rHOLD_CAPTURED\x10\x03\x12\x0f\n" +
	"\vHOLD_VOIDED\x10\x04\x12\x10\n" +
	"\fHOLD_EXPIRED\x10\x05\x12\x17\n" +
	"\x13CONVERSION_RECORDED\x10\x06\x12\x18\n" +
	"\x14TRANSACTION_REVERTED\x10\a\x12\x17\n" +
	"\x13TRANSACTION_AMENDED\x10\b\x12\x10\n" +
	"\fMETADATA_SET\x10\t\x12\x14\n" +
	"\x10METADATA_DELETED\x10\n" +
	"\x12\x13\n" +
	"\x0fSCHEMA_INSERTED\x10\v\x12\x11\n" +
	"\rPOLICY_DENIAL\x10\f\x12\x15\n" +
	"\x11APPROVAL_RECORDED\x10\rB7Z5github.com/remade/ledger/pkg/proto/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_events_proto_rawDescOnce sync.Once
	file_ledger_v1_events_proto_rawDescData []byte
)

func file_ledger_v1_events_proto_rawDescGZIP() []byte {
	file_ledger_v1_events_proto_rawDescOnce.Do(func() {
		file_ledger_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_events_proto_rawDesc), len(file_ledger_v1_events_proto_rawDesc)))
	})
	return file_ledger_v1_events_proto_rawDescData
}

var file_ledger_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ledger_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ledger_v1_events_proto_goTypes = []any{
	(EventType)(0),                     // 0: ledger.v1.EventType
	(*LogEvent)(nil),                   // 1: ledger.v1.LogEvent
	(*TransactionPostedPayload)(nil),   // 2: ledger.v1.TransactionPostedPayload
	(*HoldAuthorizedPayload)(nil),      // 3: ledger.v1.HoldAuthorizedPayload
	(*HoldCapturedPayload)(nil),        // 4: ledger.v1.HoldCapturedPayload
	(*HoldVoidedPayload)(nil),          // 5: ledger.v1.HoldVoidedPayload
	(*HoldExpiredPayload)(nil),         // 6: ledger.v1.HoldExpiredPayload
	(*ConversionRecordedPayload)(nil),  // 7: ledger.v1.ConversionRecordedPayload
	(*TransactionRevertedPayload)(nil), // 8: ledger.v1.TransactionRevertedPayload
	(*TransactionAmendedPayload)(nil),  // 9: ledger.v1.TransactionAmendedPayload
	(*MetadataSetPayload)(nil),         // 10: ledger.v1.MetadataSetPayload
	(*MetadataDeletedPayload)(nil),     // 11: ledger.v1.MetadataDeletedPayload
	(*SchemaInsertedPayload)(nil),      // 12: ledger.v1.SchemaInsertedPayload
	(*PolicyDenialPayload)(nil),        // 13: ledger.v1.PolicyDenialPayload
	(*ApprovalRecordedPayload)(nil),    // 14: ledger.v1.ApprovalRecordedPayload
	nil,                                // 15: ledger.v1.TransactionPostedPayload.MetadataEntry
	nil,                                // 16: ledger.v1.TransactionAmendedPayload.MetadataChangesEntry
	nil,                                // 17: ledger.v1.MetadataSetPayload.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*Posting)(nil),                    // 19: ledger.v1.Posting
	(*MetadataValue)(nil),              // 20: ledger.v1.MetadataValue
}
var file_ledger_v1_events_proto_depIdxs = []int32{
	18, // 0: ledger.v1.LogEvent.system_time:type_name -> google.protobuf.Timestamp
	18, // 1: ledger.v1.LogEvent.valid_time:type_name -> google.protobuf.Timestamp
	0,  // 2: ledger.v1.LogEvent.type:type_name -> ledger.v1.EventType
	19, // 3: ledger.v1.TransactionPostedPayload.postings:type_name -> ledger.v1.Posting
	15, // 4: ledger.v1.TransactionPostedPayload.metadata:type_name -> ledger.v1.TransactionPostedPayload.MetadataEntry
	18, // 5: ledger.v1.HoldAuthorizedPayload.expires_at:type_name -> google.protobuf.Timestamp
	16, // 6: ledger.v1.TransactionAmendedPayload.metadata_changes:type_name -> ledger.v1.TransactionAmendedPayload.MetadataChangesEntry
	17, // 7: ledger.v1.MetadataSetPayload.metadata:type_name -> ledger.v1.MetadataSetPayload.MetadataEntry
	20, // 8: ledger.v1.TransactionPostedPayload.MetadataEntry.value:type_name -> ledger.v1.MetadataValue
	20, // 9: ledger.v1.TransactionAmendedPayload.MetadataChangesEntry.value:type_name -> ledger.v1.MetadataValue
	20, // 10: ledger.v1.MetadataSetPayload.MetadataEntry.value:type_name -> ledger.v1.MetadataValue
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ledger_v1_events_proto_init() }
func file_ledger_v1_events_proto_init() {
	if File_ledger_v1_events_proto != nil {
		return
	}
	file_ledger_v1_ir_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_events_proto_rawDesc), len(file_ledger_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledger_v1_events_proto_goTypes,
		DependencyIndexes: file_ledger_v1_events_proto_depIdxs,
		EnumInfos:         file_ledger_v1_events_proto_enumTypes,
		MessageInfos:      file_ledger_v1_events_proto_msgTypes,
	}.Build()
	File_ledger_v1_events_proto = out.File
	file_ledger_v1_events_proto_goTypes = nil
	file_ledger_v1_events_proto_depIdxs = nil
}
