// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ledger/v1/ir.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchOperation_Mode int32

const (
	BatchOperation_ALL_OR_NOTHING BatchOperation_Mode = 0
	BatchOperation_BEST_EFFORT    BatchOperation_Mode = 1
	BatchOperation_CHECKPOINTED   BatchOperation_Mode = 2
)

// Enum value maps for BatchOperation_Mode.
var (
	BatchOperation_Mode_name = map[int32]string{
		0: "ALL_OR_NOTHING",
		1: "BEST_EFFORT",
		2: "CHECKPOINTED",
	}
	BatchOperation_Mode_value = map[string]int32{
		"ALL_OR_NOTHING": 0,
		"BEST_EFFORT":    1,
		"CHECKPOINTED":   2,
	}
)

func (x BatchOperation_Mode) Enum() *BatchOperation_Mode {
	p := new(BatchOperation_Mode)
	*p = x
	return p
}

func (x BatchOperation_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchOperation_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_ir_proto_enumTypes[0].Descriptor()
}

func (BatchOperation_Mode) Type() protoreflect.EnumType {
	return &file_ledger_v1_ir_proto_enumTypes[0]
}

func (x BatchOperation_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatchOperation_Mode.Descriptor instead.
func (BatchOperation_Mode) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{7, 0}
}

type SetMetadataOperation_TargetType int32

const (
	SetMetadataOperation_ACCOUNT     SetMetadataOperation_TargetType = 0
	SetMetadataOperation_TRANSACTION SetMetadataOperation_TargetType = 1
)

// Enum value maps for SetMetadataOperation_TargetType.
var (
	SetMetadataOperation_TargetType_name = map[int32]string{
		0: "ACCOUNT",
		1: "TRANSACTION",
	}
	SetMetadataOperation_TargetType_value = map[string]int32{
		"ACCOUNT":     0,
		"TRANSACTION": 1,
	}
)

func (x SetMetadataOperation_TargetType) Enum() *SetMetadataOperation_TargetType {
	p := new(SetMetadataOperation_TargetType)
	*p = x
	return p
}

func (x SetMetadataOperation_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetMetadataOperation_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_ir_proto_enumTypes[1].Descriptor()
}

func (SetMetadataOperation_TargetType) Type() protoreflect.EnumType {
	return &file_ledger_v1_ir_proto_enumTypes[1]
}

func (x SetMetadataOperation_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetMetadataOperation_TargetType.Descriptor instead.
func (SetMetadataOperation_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{10, 0}
}

type DeleteMetadataOperation_TargetType int32

const (
	DeleteMetadataOperation_ACCOUNT     DeleteMetadataOperation_TargetType = 0
	DeleteMetadataOperation_TRANSACTION DeleteMetadataOperation_TargetType = 1
)

// Enum value maps for DeleteMetadataOperation_TargetType.
var (
	DeleteMetadataOperation_TargetType_name = map[int32]string{
		0: "ACCOUNT",
		1: "TRANSACTION",
	}
	DeleteMetadataOperation_TargetType_value = map[string]int32{
		"ACCOUNT":     0,
		"TRANSACTION": 1,
	}
)

func (x DeleteMetadataOperation_TargetType) Enum() *DeleteMetadataOperation_TargetType {
	p := new(DeleteMetadataOperation_TargetType)
	*p = x
	return p
}

func (x DeleteMetadataOperation_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteMetadataOperation_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_ir_proto_enumTypes[2].Descriptor()
}

func (DeleteMetadataOperation_TargetType) Type() protoreflect.EnumType {
	return &file_ledger_v1_ir_proto_enumTypes[2]
}

func (x DeleteMetadataOperation_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteMetadataOperation_TargetType.Descriptor instead.
func (DeleteMetadataOperation_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{11, 0}
}

type Intent struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	LedgerId       string                    `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	ValidTime      *timestamppb.Timestamp    `protobuf:"bytes,2,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	IdempotencyKey string                    `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reference      string                    `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	Metadata       map[string]*MetadataValue `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Intent_Post
	//	*Intent_Authorize
	//	*Intent_Capture
	//	*Intent_Void
	//	*Intent_Convert
	//	*Intent_Batch
	//	*Intent_Revert
	//	*Intent_Amend
	//	*Intent_SetMetadata
	//	*Intent_DeleteMetadata
	//	*Intent_InsertSchema
	Operation     isIntent_Operation `protobuf_oneof:"operation"`
	DryRun        bool               `protobuf:"varint,30,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_ledger_v1_ir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{0}
}

func (x *Intent) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *Intent) GetValidTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTime
	}
	return nil
}

func (x *Intent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Intent) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Intent) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Intent) GetOperation() isIntent_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Intent) GetPost() *PostOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Post); ok {
			return x.Post
		}
	}
	return nil
}

func (x *Intent) GetAuthorize() *AuthorizeOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Authorize); ok {
			return x.Authorize
		}
	}
	return nil
}

func (x *Intent) GetCapture() *CaptureOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Capture); ok {
			return x.Capture
		}
	}
	return nil
}

func (x *Intent) GetVoid() *VoidOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Void); ok {
			return x.Void
		}
	}
	return nil
}

func (x *Intent) GetConvert() *ConvertOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Convert); ok {
			return x.Convert
		}
	}
	return nil
}

func (x *Intent) GetBatch() *BatchOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *Intent) GetRevert() *RevertOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Revert); ok {
			return x.Revert
		}
	}
	return nil
}

func (x *Intent) GetAmend() *AmendOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_Amend); ok {
			return x.Amend
		}
	}
	return nil
}

func (x *Intent) GetSetMetadata() *SetMetadataOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_SetMetadata); ok {
			return x.SetMetadata
		}
	}
	return nil
}

func (x *Intent) GetDeleteMetadata() *DeleteMetadataOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_DeleteMetadata); ok {
			return x.DeleteMetadata
		}
	}
	return nil
}

func (x *Intent) GetInsertSchema() *InsertSchemaOperation {
	if x != nil {
		if x, ok := x.Operation.(*Intent_InsertSchema); ok {
			return x.InsertSchema
		}
	}
	return nil
}

func (x *Intent) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type isIntent_Operation interface {
	isIntent_Operation()
}

type Intent_Post struct {
	Post *PostOperation `protobuf:"bytes,10,opt,name=post,proto3,oneof"`
}

type Intent_Authorize struct {
	Authorize *AuthorizeOperation `protobuf:"bytes,11,opt,name=authorize,proto3,oneof"`
}

type Intent_Capture struct {
	Capture *CaptureOperation `protobuf:"bytes,12,opt,name=capture,proto3,oneof"`
}

type Intent_Void struct {
	Void *VoidOperation `protobuf:"bytes,13,opt,name=void,proto3,oneof"`
}

type Intent_Convert struct {
	Convert *ConvertOperation `protobuf:"bytes,14,opt,name=convert,proto3,oneof"`
}

type Intent_Batch struct {
	Batch *BatchOperation `protobuf:"bytes,15,opt,name=batch,proto3,oneof"`
}

type Intent_Revert struct {
	Revert *RevertOperation `protobuf:"bytes,16,opt,name=revert,proto3,oneof"`
}

type Intent_Amend struct {
	Amend *AmendOperation `protobuf:"bytes,17,opt,name=amend,proto3,oneof"`
}

type Intent_SetMetadata struct {
	SetMetadata *SetMetadataOperation `protobuf:"bytes,18,opt,name=set_metadata,json=setMetadata,proto3,oneof"`
}

type Intent_DeleteMetadata struct {
	DeleteMetadata *DeleteMetadataOperation `protobuf:"bytes,19,opt,name=delete_metadata,json=deleteMetadata,proto3,oneof"`
}

type Intent_InsertSchema struct {
	InsertSchema *InsertSchemaOperation `protobuf:"bytes,20,opt,name=insert_schema,json=insertSchema,proto3,oneof"`
}

func (*Intent_Post) isIntent_Operation() {}

func (*Intent_Authorize) isIntent_Operation() {}

func (*Intent_Capture) isIntent_Operation() {}

func (*Intent_Void) isIntent_Operation() {}

func (*Intent_Convert) isIntent_Operation() {}

func (*Intent_Batch) isIntent_Operation() {}

func (*Intent_Revert) isIntent_Operation() {}

func (*Intent_Amend) isIntent_Operation() {}

func (*Intent_SetMetadata) isIntent_Operation() {}

func (*Intent_DeleteMetadata) isIntent_Operation() {}

func (*Intent_InsertSchema) isIntent_Operation() {}

type PostOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Posting             `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostOperation) Reset() {
	*x = PostOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostOperation) ProtoMessage() {}

func (x *PostOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostOperation.ProtoReflect.Descriptor instead.
func (*PostOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{1}
}

func (x *PostOperation) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_ledger_v1_ir_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{2}
}

func (x *Posting) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Posting) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Posting) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Posting) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type AuthorizeOperation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	DestinationHint string                 `protobuf:"bytes,2,opt,name=destination_hint,json=destinationHint,proto3" json:"destination_hint,omitempty"`
	Amount          string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset           string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizeOperation) Reset() {
	*x = AuthorizeOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeOperation) ProtoMessage() {}

func (x *AuthorizeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeOperation.ProtoReflect.Descriptor instead.
func (*AuthorizeOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeOperation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AuthorizeOperation) GetDestinationHint() string {
	if x != nil {
		return x.DestinationHint
	}
	return ""
}

func (x *AuthorizeOperation) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AuthorizeOperation) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *AuthorizeOperation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CaptureOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureOperation) Reset() {
	*x = CaptureOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureOperation) ProtoMessage() {}

func (x *CaptureOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureOperation.ProtoReflect.Descriptor instead.
func (*CaptureOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureOperation) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *CaptureOperation) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CaptureOperation) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type VoidOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidOperation) Reset() {
	*x = VoidOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidOperation) ProtoMessage() {}

func (x *VoidOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidOperation.ProtoReflect.Descriptor instead.
func (*VoidOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{5}
}

func (x *VoidOperation) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ConvertOperation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Source            string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination       string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	SourceAmount      string                 `protobuf:"bytes,3,opt,name=source_amount,json=sourceAmount,proto3" json:"source_amount,omitempty"`
	SourceAsset       string                 `protobuf:"bytes,4,opt,name=source_asset,json=sourceAsset,proto3" json:"source_asset,omitempty"`
	DestinationAmount string                 `protobuf:"bytes,5,opt,name=destination_amount,json=destinationAmount,proto3" json:"destination_amount,omitempty"`
	DestinationAsset  string                 `protobuf:"bytes,6,opt,name=destination_asset,json=destinationAsset,proto3" json:"destination_asset,omitempty"`
	Rate              string                 `protobuf:"bytes,7,opt,name=rate,proto3" json:"rate,omitempty"`
	RateSource        string                 `protobuf:"bytes,8,opt,name=rate_source,json=rateSource,proto3" json:"rate_source,omitempty"`
	SlippageAccount   string                 `protobuf:"bytes,9,opt,name=slippage_account,json=slippageAccount,proto3" json:"slippage_account,omitempty"`
	SlippageAmount    string                 `protobuf:"bytes,10,opt,name=slippage_amount,json=slippageAmount,proto3" json:"slippage_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConvertOperation) Reset() {
	*x = ConvertOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertOperation) ProtoMessage() {}

func (x *ConvertOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertOperation.ProtoReflect.Descriptor instead.
func (*ConvertOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertOperation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConvertOperation) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ConvertOperation) GetSourceAmount() string {
	if x != nil {
		return x.SourceAmount
	}
	return ""
}

func (x *ConvertOperation) GetSourceAsset() string {
	if x != nil {
		return x.SourceAsset
	}
	return ""
}

func (x *ConvertOperation) GetDestinationAmount() string {
	if x != nil {
		return x.DestinationAmount
	}
	return ""
}

func (x *ConvertOperation) GetDestinationAsset() string {
	if x != nil {
		return x.DestinationAsset
	}
	return ""
}

func (x *ConvertOperation) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *ConvertOperation) GetRateSource() string {
	if x != nil {
		return x.RateSource
	}
	return ""
}

func (x *ConvertOperation) GetSlippageAccount() string {
	if x != nil {
		return x.SlippageAccount
	}
	return ""
}

func (x *ConvertOperation) GetSlippageAmount() string {
	if x != nil {
		return x.SlippageAmount
	}
	return ""
}

type BatchOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          BatchOperation_Mode    `protobuf:"varint,1,opt,name=mode,proto3,enum=ledger.v1.BatchOperation_Mode" json:"mode,omitempty"`
	Intents       []*Intent              `protobuf:"bytes,2,rep,name=intents,proto3" json:"intents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperation) Reset() {
	*x = BatchOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperation) ProtoMessage() {}

func (x *BatchOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperation.ProtoReflect.Descriptor instead.
func (*BatchOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{7}
}

func (x *BatchOperation) GetMode() BatchOperation_Mode {
	if x != nil {
		return x.Mode
	}
	return BatchOperation_ALL_OR_NOTHING
}

func (x *BatchOperation) GetIntents() []*Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

type RevertOperation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OriginalTransactionId string                 `protobuf:"bytes,1,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	Force                 bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	AtEffectiveDate       bool                   `protobuf:"varint,3,opt,name=at_effective_date,json=atEffectiveDate,proto3" json:"at_effective_date,omitempty"`
	Reason                string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RevertOperation) Reset() {
	*x = RevertOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertOperation) ProtoMessage() {}

func (x *RevertOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertOperation.ProtoReflect.Descriptor instead.
func (*RevertOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{8}
}

func (x *RevertOperation) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

func (x *RevertOperation) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *RevertOperation) GetAtEffectiveDate() bool {
	if x != nil {
		return x.AtEffectiveDate
	}
	return false
}

func (x *RevertOperation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AmendOperation struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	OriginalTransactionId string                    `protobuf:"bytes,1,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	MetadataChanges       map[string]*MetadataValue `protobuf:"bytes,2,rep,name=metadata_changes,json=metadataChanges,proto3" json:"metadata_changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AmendOperation) Reset() {
	*x = AmendOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmendOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmendOperation) ProtoMessage() {}

func (x *AmendOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmendOperation.ProtoReflect.Descriptor instead.
func (*AmendOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{9}
}

func (x *AmendOperation) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

func (x *AmendOperation) GetMetadataChanges() map[string]*MetadataValue {
	if x != nil {
		return x.MetadataChanges
	}
	return nil
}

type SetMetadataOperation struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	TargetType    SetMetadataOperation_TargetType `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=ledger.v1.SetMetadataOperation_TargetType" json:"target_type,omitempty"`
	TargetId      string                          `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Metadata      map[string]*MetadataValue       `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMetadataOperation) Reset() {
	*x = SetMetadataOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetadataOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetadataOperation) ProtoMessage() {}

func (x *SetMetadataOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMetadataOperation.ProtoReflect.Descriptor instead.
func (*SetMetadataOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{10}
}

func (x *SetMetadataOperation) GetTargetType() SetMetadataOperation_TargetType {
	if x != nil {
		return x.TargetType
	}
	return SetMetadataOperation_ACCOUNT
}

func (x *SetMetadataOperation) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SetMetadataOperation) GetMetadata() map[string]*MetadataValue {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteMetadataOperation struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	TargetType    DeleteMetadataOperation_TargetType `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=ledger.v1.DeleteMetadataOperation_TargetType" json:"target_type,omitempty"`
	TargetId      string                             `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Key           string                             `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMetadataOperation) Reset() {
	*x = DeleteMetadataOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMetadataOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetadataOperation) ProtoMessage() {}

func (x *DeleteMetadataOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMetadataOperation.ProtoReflect.Descriptor instead.
func (*DeleteMetadataOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMetadataOperation) GetTargetType() DeleteMetadataOperation_TargetType {
	if x != nil {
		return x.TargetType
	}
	return DeleteMetadataOperation_ACCOUNT
}

func (x *DeleteMetadataOperation) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DeleteMetadataOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type InsertSchemaOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaBytes   []byte                 `protobuf:"bytes,1,opt,name=schema_bytes,json=schemaBytes,proto3" json:"schema_bytes,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertSchemaOperation) Reset() {
	*x = InsertSchemaOperation{}
	mi := &file_ledger_v1_ir_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSchemaOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSchemaOperation) ProtoMessage() {}

func (x *InsertSchemaOperation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSchemaOperation.ProtoReflect.Descriptor instead.
func (*InsertSchemaOperation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{12}
}

func (x *InsertSchemaOperation) GetSchemaBytes() []byte {
	if x != nil {
		return x.SchemaBytes
	}
	return nil
}

func (x *InsertSchemaOperation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type MetadataValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetadataValue_StringValue
	//	*MetadataValue_IntValue
	//	*MetadataValue_BoolValue
	//	*MetadataValue_DecimalValue
	//	*MetadataValue_TimestampValue
	Value         isMetadataValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	mi := &file_ledger_v1_ir_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ir_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ir_proto_rawDescGZIP(), []int{13}
}

func (x *MetadataValue) GetValue() isMetadataValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetadataValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MetadataValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetadataValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MetadataValue) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

func (x *MetadataValue) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

type isMetadataValue_Value interface {
	isMetadataValue_Value()
}

type MetadataValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MetadataValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetadataValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MetadataValue_DecimalValue struct {
	DecimalValue string `protobuf:"bytes,4,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

type MetadataValue_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

func (*MetadataValue_StringValue) isMetadataValue_Value() {}

func (*MetadataValue_IntValue) isMetadataValue_Value() {}

func (*MetadataValue_BoolValue) isMetadataValue_Value() {}

func (*MetadataValue_DecimalValue) isMetadataValue_Value() {}

func (*MetadataValue_TimestampValue) isMetadataValue_Value() {}

var File_ledger_v1_ir_proto protoreflect.FileDescriptor

const file_ledger_v1_ir_proto_rawDesc = "" +
	"\n" +
	"\x12ledger/v1/ir.proto\x12\tledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\a\n" +
	"\x06Intent\x12\x1b\n" +
	"\tledger_id\x18\x01 \x01(\tR\bledgerId\x129\n" +
	"\n" +
	"valid_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidTime\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1c\n" +
	"\treference\x18\x04 \x01(\tR\treference\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.ledger.v1.Intent.MetadataEntryR\bmetadata\x12.\n" +
	"\x04post\x18\n" +
	" \x01(\v2\x18.ledger.v1.PostOperationH\x00R\x04post\x12=\n" +
	"\tauthorize\x18\v \x01(\v2\x1d.ledger.v1.AuthorizeOperationH\x00R\tauthorize\x127\n" +
	"\acapture\x18\f \x01(\v2\x1b.ledger.v1.CaptureOperationH\x00R\acapture\x12.\n" +
	"\x04void\x18\r \x01(\v2\x18.ledger.v1.VoidOperationH\x00R\x04void\x127\n" +
	"\aconvert\x18\x0e \x01(\v2\x1b.ledger.v1.ConvertOperationH\x00R\aconvert\x121\n" +
	"\x05batch\x18\x0f \x01(\v2\x19.ledger.v1.BatchOperationH\x00R\x05batch\x124\n" +
	"\x06revert\x18\x10 \x01(\v2\x1a.ledger.v1.RevertOperationH\x00R\x06revert\x121\n" +
	"\x05amend\x18\x11 \x01(\v2\x19.ledger.v1.AmendOperationH\x00R\x05amend\x12D\n" +
	"\fset_metadata\x18\x12 \x01(\v2\x1f.ledger.v1.SetMetadataOperationH\x00R\vsetMetadata\x12M\n" +
	"\x0fdelete_metadata\x18\x13 \x01(\v2\".ledger.v1.DeleteMetadataOperationH\x00R\x0edeleteMetadata\x12G\n" +
	"\rinsert_schema\x18\x14 \x01(\v2 .ledger.v1.InsertSchemaOperationH\x00R\finsertSchema\x12\x17\n" +
	"\adry_run\x18\x1e \x01(\bR\x06dryRun\x1aU\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ledger.v1.MetadataValueR\x05value:\x028\x01B\v\n" +
	"\toperation\"?\n" +
	"\rPostOperation\x12.\n" +
	"\bpostings\x18\x01 \x03(\v2\x12.ledger.v1.PostingR\bpostings\"q\n" +
	"\aPosting\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\"\xc0\x01\n" +
	"\x12AuthorizeOperation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12)\n" +
	"\x10destination_hint\x18\x02 \x01(\tR\x0fdestinationHint\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"e\n" +
	"\x10CaptureOperation\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\"(\n" +
	"\rVoidOperation\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"\xf9\x02\n" +
	"\x10ConvertOperation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12#\n" +
	"\rsource_amount\x18\x03 \x01(\tR\fsourceAmount\x12!\n" +
	"\fsource_asset\x18\x04 \x01(\tR\vsourceAsset\x12-\n" +
	"\x12destination_amount\x18\x05 \x01(\tR\x11destinationAmount\x12+\n" +
	"\x11destination_asset\x18\x06 \x01(\tR\x10destinationAsset\x12\x12\n" +
	"\x04rate\x18\a \x01(\tR\x04rate\x12\x1f\n" +
	"\vrate_source\x18\b \x01(\tR\n" +
	"rateSource\x12)\n" +
	"\x10slippage_account\x18\t \x01(\tR\x0fslippageAccount\x12'\n" +
	"\x0fslippage_amount\x18\n" +
	" \x01(\tR\x0eslippageAmount\"\xb0\x01\n" +
	"\x0eBatchOperation\x122\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1e.ledger.v1.BatchOperation.ModeR\x04mode\x12+\n" +
	"\aintents\x18\x02 \x03(\v2\x11.ledger.v1.IntentR\aintents\"=\n" +
	"\x04Mode\x12\x12\n" +
	"\x0eALL_OR_NOTHING\x10\x00\x12\x0f\n" +
	"\vBEST_EFFORT\x10\x01\x12\x10\n" +
	"\fCHECKPOINTED\x10\x02\"\xa3\x01\n" +
	"\x0fRevertOperation\x126\n" +
	"\x17original_transaction_id\x18\x01 \x01(\tR\x15originalTransactionId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12*\n" +
	"\x11at_effective_date\x18\x03 \x01(\bR\x0fatEffectiveDate\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x81\x02\n" +
	"\x0eAmendOperation\x126\n" +
	"\x17original_transaction_id\x18\x01 \x01(\tR\x15originalTransactionId\x12Y\n" +
	"\x10metadata_changes\x18\x02 \x03(\v2..ledger.v1.AmendOperation.MetadataChangesEntryR\x0fmetadataChanges\x1a\\\n" +
	"\x14MetadataChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ledger.v1.MetadataValueR\x05value:\x028\x01\"\xce\x02\n" +
	"\x14SetMetadataOperation\x12K\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2*.ledger.v1.SetMetadataOperation.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.ledger.v1.SetMetadataOperation.MetadataEntryR\bmetadata\x1aU\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.ledger.v1.MetadataValueR\x05value:\x028\x01\"*\n" +
	"\n" +
	"TargetType\x12\v\n" +
	"\aACCOUNT\x10\x00\x12\x0f\n" +
	"\vTRANSACTION\x10\x01\"\xc4\x01\n" +
	"\x17DeleteMetadataOperation\x12N\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2-.ledger.v1.DeleteMetadataOperation.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"*\n" +
	"\n" +
	"TargetType\x12\v\n" +
	"\aACCOUNT\x10\x00\x12\x0f\n" +
	"\vTRANSACTION\x10\x01\"T\n" +
	"\x15InsertSchemaOperation\x12!\n" +
	"\fschema_bytes\x18\x01 \x01(\fR\vschemaBytes\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xeb\x01\n" +
	"\rMetadataValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12%\n" +
	"\rdecimal_value\x18\x04 \x01(\tH\x00R\fdecimalValue\x12E\n" +
	"\x0ftimestamp_value\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValueB\a\n" +
	"\x05valueB7Z5github.com/remade/ledger/pkg/proto/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_ir_proto_rawDescOnce sync.Once
	file_ledger_v1_ir_proto_rawDescData []byte
)

func file_ledger_v1_ir_proto_rawDescGZIP() []byte {
	file_ledger_v1_ir_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ir_proto_rawDesc), len(file_ledger_v1_ir_proto_rawDesc)))
	})
	return file_ledger_v1_ir_proto_rawDescData
}

var file_ledger_v1_ir_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ledger_v1_ir_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ledger_v1_ir_proto_goTypes = []any{
	(BatchOperation_Mode)(0),                // 0: ledger.v1.BatchOperation.Mode
	(SetMetadataOperation_TargetType)(0),    // 1: ledger.v1.SetMetadataOperation.TargetType
	(DeleteMetadataOperation_TargetType)(0), // 2: ledger.v1.DeleteMetadataOperation.TargetType
	(*Intent)(nil),                          // 3: ledger.v1.Intent
	(*PostOperation)(nil),                   // 4: ledger.v1.PostOperation
	(*Posting)(nil),                         // 5: ledger.v1.Posting
	(*AuthorizeOperation)(nil),              // 6: ledger.v1.AuthorizeOperation
	(*CaptureOperation)(nil),                // 7: ledger.v1.CaptureOperation
	(*VoidOperation)(nil),                   // 8: ledger.v1.VoidOperation
	(*ConvertOperation)(nil),                // 9: ledger.v1.ConvertOperation
	(*BatchOperation)(nil),                  // 10: ledger.v1.BatchOperation
	(*RevertOperation)(nil),                 // 11: ledger.v1.RevertOperation
	(*AmendOperation)(nil),                  // 12: ledger.v1.AmendOperation
	(*SetMetadataOperation)(nil),            // 13: ledger.v1.SetMetadataOperation
	(*DeleteMetadataOperation)(nil),         // 14: ledger.v1.DeleteMetadataOperation
	(*InsertSchemaOperation)(nil),           // 15: ledger.v1.InsertSchemaOperation
	(*MetadataValue)(nil),                   // 16: ledger.v1.MetadataValue
	nil,                                     // 17: ledger.v1.Intent.MetadataEntry
	nil,                                     // 18: ledger.v1.AmendOperation.MetadataChangesEntry
	nil,                                     // 19: ledger.v1.SetMetadataOperation.MetadataEntry
	(*timestamppb.Timestamp)(nil),           // 20: google.protobuf.Timestamp
}
var file_ledger_v1_ir_proto_depIdxs = []int32{
	20, // 0: ledger.v1.Intent.valid_time:type_name -> google.protobuf.Timestamp
	17, // 1: ledger.v1.Intent.metadata:type_name -> ledger.v1.Intent.MetadataEntry
	4,  // 2: ledger.v1.Intent.post:type_name -> ledger.v1.PostOperation
	6,  // 3: ledger.v1.Intent.authorize:type_name -> ledger.v1.AuthorizeOperation
	7,  // 4: ledger.v1.Intent.capture:type_name -> ledger.v1.CaptureOperation
	8,  // 5: ledger.v1.Intent.void:type_name -> ledger.v1.VoidOperation
	9,  // 6: ledger.v1.Intent.convert:type_name -> ledger.v1.ConvertOperation
	10, // 7: ledger.v1.Intent.batch:type_name -> ledger.v1.BatchOperation
	11, // 8: ledger.v1.Intent.revert:type_name -> ledger.v1.RevertOperation
	12, // 9: ledger.v1.Intent.amend:type_name -> ledger.v1.AmendOperation
	13, // 10: ledger.v1.Intent.set_metadata:type_name -> ledger.v1.SetMetadataOperation
	14, // 11: ledger.v1.Intent.delete_metadata:type_name -> ledger.v1.DeleteMetadataOperation
	15, // 12: ledger.v1.Intent.insert_schema:type_name -> ledger.v1.InsertSchemaOperation
	5,  // 13: ledger.v1.PostOperation.postings:type_name -> ledger.v1.Posting
	20, // 14: ledger.v1.AuthorizeOperation.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 15: ledger.v1.BatchOperation.mode:type_name -> ledger.v1.BatchOperation.Mode
	3,  // 16: ledger.v1.BatchOperation.intents:type_name -> ledger.v1.Intent
	18, // 17: ledger.v1.AmendOperation.metadata_changes:type_name -> ledger.v1.AmendOperation.MetadataChangesEntry
	1,  // 18: ledger.v1.SetMetadataOperation.target_type:type_name -> ledger.v1.SetMetadataOperation.TargetType
	19, // 19: ledger.v1.SetMetadataOperation.metadata:type_name -> ledger.v1.SetMetadataOperation.MetadataEntry
	2,  // 20: ledger.v1.DeleteMetadataOperation.target_type:type_name -> ledger.v1.DeleteMetadataOperation.TargetType
	20, // 21: ledger.v1.MetadataValue.timestamp_value:type_name -> google.protobuf.Timestamp
	16, // 22: ledger.v1.Intent.MetadataEntry.value:type_name -> ledger.v1.MetadataValue
	16, // 23: ledger.v1.AmendOperation.MetadataChangesEntry.value:type_name -> ledger.v1.MetadataValue
	16, // 24: ledger.v1.SetMetadataOperation.MetadataEntry.value:type_name -> ledger.v1.MetadataValue
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_ledger_v1_ir_proto_init() }
func file_ledger_v1_ir_proto_init() {
	if File_ledger_v1_ir_proto != nil {
		return
	}
	file_ledger_v1_ir_proto_msgTypes[0].OneofWrappers = []any{
		(*Intent_Post)(nil),
		(*Intent_Authorize)(nil),
		(*Intent_Capture)(nil),
		(*Intent_Void)(nil),
		(*Intent_Convert)(nil),
		(*Intent_Batch)(nil),
		(*Intent_Revert)(nil),
		(*Intent_Amend)(nil),
		(*Intent_SetMetadata)(nil),
		(*Intent_DeleteMetadata)(nil),
		(*Intent_InsertSchema)(nil),
	}
	file_ledger_v1_ir_proto_msgTypes[13].OneofWrappers = []any{
		(*MetadataValue_StringValue)(nil),
		(*MetadataValue_IntValue)(nil),
		(*MetadataValue_BoolValue)(nil),
		(*MetadataValue_DecimalValue)(nil),
		(*MetadataValue_TimestampValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ir_proto_rawDesc), len(file_ledger_v1_ir_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledger_v1_ir_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ir_proto_depIdxs,
		EnumInfos:         file_ledger_v1_ir_proto_enumTypes,
		MessageInfos:      file_ledger_v1_ir_proto_msgTypes,
	}.Build()
	File_ledger_v1_ir_proto = out.File
	file_ledger_v1_ir_proto_goTypes = nil
	file_ledger_v1_ir_proto_depIdxs = nil
}
