// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ledger/v1/stream.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LedgerId          string                 `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	AccountPatterns   []string               `protobuf:"bytes,2,rep,name=account_patterns,json=accountPatterns,proto3" json:"account_patterns,omitempty"`
	Types             []EventType            `protobuf:"varint,3,rep,packed,name=types,proto3,enum=ledger.v1.EventType" json:"types,omitempty"`
	FromEventId       string                 `protobuf:"bytes,4,opt,name=from_event_id,json=fromEventId,proto3" json:"from_event_id,omitempty"`
	IncludeHistorical bool                   `protobuf:"varint,5,opt,name=include_historical,json=includeHistorical,proto3" json:"include_historical,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ledger_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *SubscribeRequest) GetAccountPatterns() []string {
	if x != nil {
		return x.AccountPatterns
	}
	return nil
}

func (x *SubscribeRequest) GetTypes() []EventType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SubscribeRequest) GetFromEventId() string {
	if x != nil {
		return x.FromEventId
	}
	return ""
}

func (x *SubscribeRequest) GetIncludeHistorical() bool {
	if x != nil {
		return x.IncludeHistorical
	}
	return false
}

type SubscriptionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *LogEvent              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	IsReplay      bool                   `protobuf:"varint,2,opt,name=is_replay,json=isReplay,proto3" json:"is_replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent) Reset() {
	*x = SubscriptionEvent{}
	mi := &file_ledger_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent) ProtoMessage() {}

func (x *SubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_ledger_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionEvent) GetEvent() *LogEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscriptionEvent) GetIsReplay() bool {
	if x != nil {
		return x.IsReplay
	}
	return false
}

var File_ledger_v1_stream_proto protoreflect.FileDescriptor

const file_ledger_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/stream.proto\x12\tledger.v1\x1a\x16ledger/v1/events.proto\"\xd9\x01\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tledger_id\x18\x01 \x01(\tR\bledgerId\x12)\n" +
	"\x10account_patterns\x18\x02 \x03(\tR\x0faccountPatterns\x12*\n" +
	"\x05types\x18\x03 \x03(\x0e2\x14.ledger.v1.EventTypeR\x05types\x12\"\n" +
	"\rfrom_event_id\x18\x04 \x01(\tR\vfromEventId\x12-\n" +
	"\x12include_historical\x18\x05 \x01(\bR\x11includeHistorical\"[\n" +
	"\x11SubscriptionEvent\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x13.ledger.v1.LogEventR\x05event\x12\x1b\n" +
	"\tis_replay\x18\x02 \x01(\bR\bisReplayB7Z5github.com/remade/ledger/pkg/proto/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_stream_proto_rawDescOnce sync.Once
	file_ledger_v1_stream_proto_rawDescData []byte
)

func file_ledger_v1_stream_proto_rawDescGZIP() []byte {
	file_ledger_v1_stream_proto_rawDescOnce.Do(func() {
		file_ledger_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_stream_proto_rawDesc), len(file_ledger_v1_stream_proto_rawDesc)))
	})
	return file_ledger_v1_stream_proto_rawDescData
}

var file_ledger_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ledger_v1_stream_proto_goTypes = []any{
	(*SubscribeRequest)(nil),  // 0: ledger.v1.SubscribeRequest
	(*SubscriptionEvent)(nil), // 1: ledger.v1.SubscriptionEvent
	(EventType)(0),            // 2: ledger.v1.EventType
	(*LogEvent)(nil),          // 3: ledger.v1.LogEvent
}
var file_ledger_v1_stream_proto_depIdxs = []int32{
	2, // 0: ledger.v1.SubscribeRequest.types:type_name -> ledger.v1.EventType
	3, // 1: ledger.v1.SubscriptionEvent.event:type_name -> ledger.v1.LogEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ledger_v1_stream_proto_init() }
func file_ledger_v1_stream_proto_init() {
	if File_ledger_v1_stream_proto != nil {
		return
	}
	file_ledger_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_stream_proto_rawDesc), len(file_ledger_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledger_v1_stream_proto_goTypes,
		DependencyIndexes: file_ledger_v1_stream_proto_depIdxs,
		MessageInfos:      file_ledger_v1_stream_proto_msgTypes,
	}.Build()
	File_ledger_v1_stream_proto = out.File
	file_ledger_v1_stream_proto_goTypes = nil
	file_ledger_v1_stream_proto_depIdxs = nil
}
